### ISSUE TITLE
app assets are not accessible behind nginx proxy on kubernetes

### ISSUE THREAD

**Issue by rvashishth** [apache/pulsar-manager#266]
[Similar issue on another pulsar-dashboard](https://github.com/bbonnin/pulsar-express/issues/19). 

Pulsar-manager web dashboard never loads up when we host pulsar-manager behind an LB/Proxy service with a url slug.

It looks like all the static contents are loaded from the absolute path instead of the relative path.

**Comment by sijie** [comment]
@rvashishth do you have an example how do you set up the LB/proxy?

**Comment by enriched** [comment]
Running into the same issue, using [Ambassador](https://www.getambassador.io/docs/latest/topics/using/rewrites/) with a helm templated service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pulsar-manager-http
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: "{{ .Release.Name }}-pulsar-manager"
      prefix: /pulsar/
      service: "{{ .Release.Name }}-pulsar-manager-http:9527"
  labels:
    app: pulsar
    cluster: {{ .Release.Name }}-pulsar
    component: pulsar-manager
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: frontend
    port: 9527
    protocol: TCP
    targetPort: 9527
  selector:
    app: pulsar
    component: pulsar-manager
    release: {{ .Release.Name }}
  sessionAffinity: None
```
Running locally on Docker for Mac the request to http://localhost/pulsar/ responds with a 200 and html:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8>
  <meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
  <meta name=renderer content=webkit>
  <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <title>Pulsar Admin UI</title>
  <link rel="shortcut icon" href=/favicon.ico>
  <link href=/static/css/chunk-elementUI.31757218.css rel=stylesheet>
  <link href=/static/css/chunk-libs.bd17d456.css rel=stylesheet>
  <link href=/static/css/app.b2eade8f.css rel=stylesheet>
</head>
<body>
  <div id=app></div>
  <script>redacted for brevity</script>
  <script src=/static/js/chunk-elementUI.ab5927a0.js></script>
  <script src=/static/js/chunk-libs.1395be8a.js></script>
  <script src=/static/js/app.1ecd3f65.js></script>
</body>
</html>
```

requests to get stylesheets and scripts under the `/static/` all go to `localhost/static/...` and return 404 rather than `localhost/pulsar/static/...` where I would expect them to be able to find the resources.
