### ISSUE TITLE
Unable to get a functioning docker-compose setup working with pulsar-manager

### ISSUE THREAD

**Issue by kdawgwilk** [apache/pulsar-manager#279]
I am working on spinning up both `pulsar` and `pulsar-manager` together using docker-compose and I can get both of them up and running but many things appear to be broken.  I am unable to load clusters or create them.  I
`docker-compose.yml`
```yml
version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar:2.5.0
    command: bin/pulsar standalone -a localhost
    ports:
      - "8080:8080"
      - "6650:6650"
    restart: unless-stopped
    volumes:
      - "./data/:/pulsar/data"
      - "./conf/client.conf:/pulsar/conf/client.conf"
      - "./conf/standalone.conf:/pulsar/conf/standalone.conf"
  dashboard:
    image: apachepulsar/pulsar-manager:v0.1.0
    ports:
      - "9527:9527"
    depends_on:
      - pulsar
    volumes:
      - "./data/:/data"
    environment:
      REDIRECT_HOST: "http://127.0.0.1"
      REDIRECT_PORT: "9527"
      DRIVER_CLASS_NAME: "org.postgresql.Driver"
      URL: "jdbc:postgresql://127.0.0.1:5432/pulsar_manager"
      USERNAME: "pulsar"
      PASSWORD: "pulsar"
      LOG_LEVEL: "DEBUG"
```
Then open `pulsar-manager` in browser at http://localhost:9527 login with:
- user: `pulsar`
- pass: `pulsar`
Create an environment:
- Name: `docker`
- Service Url: `http://pulsar:8080` (pulsar host gets mapped to the other container automatically by docker's networking)

This seems to fail but if you refresh the environment shows up in the list? 
Then try to view clusters which fails.  which means I cannot create tenants.
