### ISSUE TITLE
Pulsar Manager keeps saying "This environment is error. Please check it"

### ISSUE THREAD

**Issue by mikayeln** [apache/pulsar-manager#283]
OS: 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

Hi,
I have Pulsar instance running in standalone mode.
Also I started Pulsar-Manager with docker. Here is the command line:
`docker run -it -p 9527:9527 -e REDIRECT_HOST=http://127.0.0.1 -e REDIRECT_PORT=9527 -e DRIVER_CLASS_NAME=org.postgresql.Driver -e URL='jdbc:postgresql://127.0.0.1:5432/pulsar_manager' -e USERNAME=pulsar -e PASSWORD=pulsar -e LOG_LEVEL=DEBUG -v $PWD:/data apachepulsar/pulsar-manager:v0.1.0 /bin/sh`

On Add Environment action 
![image](https://user-images.githubusercontent.com/5030123/77766965-f5c2fa00-7072-11ea-80f6-e913595e1155.png)
i'm getting following error
![image](https://user-images.githubusercontent.com/5030123/77767048-0ffcd800-7073-11ea-9fd5-b2b5c7febd34.png)

But there is no any errors in the logs of Pulsar. 

Did I miss some configuraion?

Thanks.

**Comment by tuteng** [comment]
Please check whether your broker's network is connected and whether your service URL is port 8888? @mikayeln

**Comment by mikayeln** [comment]
@tuteng Thanks for reply.
URL port is 8888. 
I'm able to connect to pulsar from pulsar java client.
Also, I checked the code of manager and found out that error occurs on GET request to /metrics. 
From browser I was able to get the metrics.

**Comment by tuteng** [comment]
I think you should try to check whether you can connect to the pulsar cluster in the container running `pulsar-manager`. @mikayeln 

```
docker exec -it container_id /bin/sh
curl -v http://broker-ip:8888/metrics/
```

**Comment by mehran-prs** [comment]
it's because _pulsar_  and _pulsar-manger_ runs in different containers with theirself localhosts (each container just know itself `localhost`).
you should either run these two containers in one network using something like docker composer, or set `--network host` in your command, something like this:
```bash
docker run --rm --network host -it  -e REDIRECT_HOST=http://localhost -e REDIRECT_PORT=9527 -e DRIVER_CLASS_NAME=org.postgresql.Driver -e URL='jdbc:postgresql://127.0.0.1:5432/pulsar_manager' -e USERNAME=pulsar -e PASSWORD=pulsar -e LOG_LEVEL=DEBUG -v $PWD:/data apachepulsar/pulsar-manager:v0.1.0 /bin/sh
```

**Comment by sijie** [comment]
@mehran-prs thank you for the comment!

It would be great if we can add this example to README. Are you interested in contributing a fix?

**Comment by lzhpo** [comment]
I also encountered this problem. How did you solve it?
My port is 8080, my curl-v http://127.0.0.1 : 8080 / metrics / has data.

**Comment by lzhpo** [comment]
I also encountered this problem. How did you solve it?
My port is 8080, my curl-v http://127.0.0.1:8080/metrics/ has data.

**Comment by lzhpo** [comment]
@sijie @mikayeln 
I have solved this problem. Do not use localhost or 127.0.0.1. Please use IP address, http://<Your IP>:8080, it will work! such as http://192.168.100.200:8080
Hope it works for you!
Thank you!

**Comment by josuemotte** [comment]
> @mehran-prs thank you for the comment!
> 
> It would be great if we can add this example to README. Are you interested in contributing a fix?

@sijie 

PR Created #314

**Comment by KVINTH** [comment]
Hi I am also receiving this same message after cloning the repo and using docker compose to start up the services.

When adding an environment I attempted to use the following for the Service URL:
pulsar://localhost:6650
http://localhost:8080
http://pulsar-standalone:8080

all of which resulted in the same error message.

**Comment by mipper** [comment]
> Hi I am also receiving this same message on Windows 10 after cloning the repo and using docker compose to start up the services.
> 
> When adding an environment I attempted to use the following for the Service URL:
> pulsar://localhost:6650
> http://localhost:8080
> http://pulsar-standalone:8080
> 
> all of which resulted in the same error message.

For anyone else being blocked by this, it's again, because of the docker network.  If you use http://proxy1:8080 you should be okay as this is the name of the container that's running the front proxy in the docker-compose environment.  You can see the details of this by running `docker network inspect kitchen-sink_pulsar`

**Comment by jamesvsshark** [comment]
Using `http://pulsar:8080` as the service url works for me.

**Comment by vip32** [comment]
pfoeh, that was hard, This worked for me eventually

docker-compose
```
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: shop_pulsar
    command: bin/pulsar standalone
    hostname: pulsar
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - ./tools/pulsar/data:/pulsar/data
    ports:
      - 6650:6650
      - 8080:8080 # http://localhost:8080/metrics/
    restart: unless-stopped
    networks:
      - acme

  pulsar-manager: 
    image: apachepulsar/pulsar-manager:latest
    container_name: shop_pulsar_manager
    ports:
      - 9527:9527 # http://localhost:9527 (login:pulsar/pulsar)
      - 7750:7750
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    networks:
      - acme
```

### create a super-user using the following commands 
- shell into shop_pulsar_manager container
- `apk add curl`
- `CSRF_TOKEN=$(curl http://shop_pulsar_manager:7750/pulsar-manager/csrf-token)`
- `curl --verbose -H 'X-XSRF-TOKEN: $CSRF_TOKEN' -H 'Cookie: XSRF-TOKEN=$CSRF_TOKEN;' -H 'Content-Type: application/json' -X PUT http://shop_pulsar_manager:7750/pulsar-manager/users/superuser -d '{"name": "pulsar", "password": "pulsar", "description": "Pulsar Manager Admin", "email": "support@pulsar.io"}'`

### create a new environment
- open browser http://localhost:9527 and login with pulsar/pulsar
- choose '+ new environment'
- name=shop, service url=http://pulsar:8080

now have ro find a way to automate this within docker-compose....
