### ISSUE TITLE
Pulsar Manager UI not working

### ISSUE THREAD

**Issue by sivavijay13** [apache/pulsar-manager#284]
![image](https://user-images.githubusercontent.com/46527272/78127268-77c77000-7431-11ea-91f3-ad3216c06add.png)
after starting pulsar manager when i access it it shows 500 error only not loading configured details

**Comment by tuteng** [comment]
Please check pulsar-manager.log @sivavijay13

**Comment by sijie** [comment]
@sivavijay13 Are you able to find any errors in the pulsar-manager.log? Or can you provide more details about it?

**Comment by Persi** [comment]
@sivavijay13 did you try to use an external database? That was the reason why i got this errors all the time, I opened #294 to clarify the current Docker image state.

**Comment by sivavijay13** [comment]
I was starting both pulsar & pulsar manager as docker image, After which I just naving to UI of pulsar manager where I got this error

**Comment by Persi** [comment]
To get the logs of the internal backend on your local machine you could configure it like the following in your docker-compose file:

```
    environment:
      ...
      SPRING_APPLICATION_JSON : |
        {
         "logging": { "file": "/logs/backend.log"}
        }
      ...
    volumes:
      - /your_local_homepath/whatever_folder:/logs
```

**Comment by wburon** [comment]
I'm facing the same issue. 
Thanks @Persi to share how to get logs.
It seems to be a problem with the internal database in my case.
I got "Failed to obtain JDBC Connection".
`### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
### The error may exist in org/apache/pulsar/manager/mapper/EnvironmentsMapper.java (best guess)
### The error may involve org.apache.pulsar.manager.mapper.EnvironmentsMapper.findByName
### The error occurred while executing a query`

**Comment by tuteng** [comment]
Can you share your configuration and use a custom database? @wburon

**Comment by wburon** [comment]
sure !
I use Docker Desktop for Windows 10.
```yml
version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar:2.5.0
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    restart: unless-stopped
    volumes:
      - pulsardata:/pulsar/data
  dashboard:
    image: apachepulsar/pulsar-manager:v0.1.0
    ports:
      - "9527:9527"
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      REDIRECT_HOST: "http://127.0.0.1"
      REDIRECT_PORT: "9527"
      DRIVER_CLASS_NAME: "org.postgresql.Driver"
      URL: "jdbc:postgresql://127.0.0.1:5432/pulsar_manager"
      USERNAME: "pulsar"
      PASSWORD: "pulsar"
      LOG_LEVEL: "DEBUG"
      SPRING_APPLICATION_JSON : |
        {
         "logging": { "file": "/logs/backend.log"}
        }
    volumes:
      - ./logs:/logs
      - pulsarui:/data
volumes:
  pulsarui:
  pulsardata:
```

**Comment by tuteng** [comment]
I want to confirm one thing, do you have permission to write data in the folder `pulsarui`, The database connection is not available, it is possible that the internal database did not start successfully. @wburon

**Comment by wburon** [comment]
I'm pretty new with docker. Your asking me this ? @tuteng 
```yml
        "Mounts": [
            {
                "Type": "volume",
                "Name": "docker_pulsarui",
                "Source": "/var/lib/docker/volumes/docker_pulsarui/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/c/programJava/Pulsar/pulsar-manager/docker/logs",
                "Destination": "/logs",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```
> it is possible that the internal database did not start successfully

Maybe you're right because what i have in the pulsar-manger ui is not what i see in the readme's  example.
