### ISSUE TITLE
Starting Docker container pulsar-manager-0.3.0 with internal PostreSQL does not work

### ISSUE THREAD

**Issue by malaskowski** [apache/pulsar-manager#505]
Running Pulsar Manager with the default [Pulsar Helm Chart settings](https://github.com/apache/pulsar-helm-chart/blob/pulsar-3.0.0/charts/pulsar/values.yaml#L1051) ends with not working manager instance.

## Steps to reproduce
Run the container using the default: 
   ```bash
   docker pull apachepulsar/pulsar-manager:v0.3.0
   docker run -it \
      -p 9527:9527 -p 7750:7750 \
      -e REDIRECT_HOST="http://127.0.0.1" \
      -e REDIRECT_PORT="9527" \
      -e DRIVER_CLASS_NAME="org.postgresql.Driver" \
      -e URL="jdbc:postgresql://127.0.0.1:5432/pulsar_manager" \
      -e USERNAME="pulsar" \
      -e PASSWORD="pulsar" \
      -e LOG_LEVEL="DEBUG" \
      apachepulsar/pulsar-manager:v0.3.0
   ```

## Result
First, the user is asked for the information by the `adduser` command from the https://github.com/apache/pulsar-manager/blob/v0.3.0/docker/entrypoint.sh#L27 (looks like fix for this is pretty easy: `adduser --disabled-password --gecos "" --ingroup pulsar pulsar`). However, later running the `/pulsar-manager/startup.sh` fails with:

```bash
/pulsar-manager/startup.sh: 21: initdb: not found
/pulsar-manager/startup.sh: 22: pg_ctl: not found
createdb: error: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: error: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

Then in the `/pulsar-manager/pulsar-manager.log` you can see the connection error (as the DB didn't start):
```bash
2023-01-13 10:49:51.463 ERROR 156 --- [pool-2-thread-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

Finally, the backend never starts properly.

## Expected result
The Pulsar Manager creates an internal DB instance and runs properly.

## Additional details
I'm running the command above on M1 Apple Silicon processor and Docker Desktop for Mac `v4.15.0`.

**Comment by splio-rbechon** [comment]
Hello @malaskowski 

It seems that there is an issue in startup script. Database can't be created because binary path is not in the environment variable PATH.
Another related issue has been created [here](https://github.com/apache/pulsar-manager/issues/465)
You can find a commit that will provide you a way to fix this [here](https://github.com/apache/pulsar-manager/pull/478/commits/25aab24fc92fc7ed92eca101c15d1a65656178b6)

Unfortunately, you docker will fail each time during init so you will have to fix this manually until the patch is deployed

Have a nice day
Robin

**Comment by doug-ba** [comment]
@splio-rbechon , the fix was committed in August of 2022.  Is there any chance of getting a new container image release?  The last release is effectively broken.

**Comment by doug-ba** [comment]
@tuteng , sorry to ping you directly, but it looks like you push the container images.  Is there any chance of getting a new version of the pulsar-manager with the fix for this pushed?

**Comment by tuteng** [comment]
@urfreespace Can you help take a look at it? thanks

**Comment by bpereto** [comment]
@urfreespace @splio-rbechon @nodece 
can someone of you release (or poke the maintainer) to release a new release with commit https://github.com/apache/pulsar-manager/pull/478/commits/25aab24fc92fc7ed92eca101c15d1a65656178b6 included?

thank you!

**Comment by Zand3r24** [comment]
Just wanted to say I'm also hitting this, and waiting for a new image to be built with the fix.

**Comment by tuteng** [comment]
[streamnative/pulsar-manager:v0.3.1-rc2](https://hub.docker.com/layers/streamnative/pulsar-manager/v0.3.1-rc2/images/sha256-2b1f9eaac6300f4a1d5a5e8cfd03a7ed789056fb8db4757f52d056c5199a716e?context=explore)

Since the official release may take some time, I tried to build an image manually, can you try it? @bpereto @Zand3r24 @doug-ba @malaskowski @splio-rbechon

**Comment by tisonkun** [comment]
@tuteng Out of curiosity, are you working on v0.3.1 release based on current master branch?

**Comment by Aaron-ML** [comment]
Hitting this as well, looks like a lot of this stuff is on hold or what?

**Comment by malaskowski** [comment]
@tuteng 
I was still prompted on `docker run`:

```
Enter the new value, or press ENTER for the default
	Full Name []:
	Room Number []:
	Work Phone []:
	Home Phone []:
	Other []:
Is the information correct? [Y/n] Y
```

But manager started correctly and works, thank you.

**Comment by bpereto** [comment]
^

> [streamnative/pulsar-manager:v0.3.1-rc2](https://hub.docker.com/layers/streamnative/pulsar-manager/v0.3.1-rc2/images/sha256-2b1f9eaac6300f4a1d5a5e8cfd03a7ed789056fb8db4757f52d056c5199a716e?context=explore)
> 
> Since the official release may take some time, I tried to build an image manually, can you try it? @bpereto @Zand3r24 @doug-ba @malaskowski @splio-rbechon

keeps crashing:
```
2023-05-10 15:28:19,418 INFO success: pulsar-manager-backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-10 15:28:19,418 INFO exited: pulsar-manager-backend (exit status 1; not expected)
2023-05-10 15:28:20,422 INFO spawned: 'pulsar-manager-backend' with pid 1145
 ```

**Comment by bpereto** [comment]
@tisonkun I will test [v0.4.0-candidate-2](https://github.com/apache/pulsar-manager/releases/tag/v0.4.0-candidate-2) if you will release a docker image.

**Comment by bpereto** [comment]
I builded the docker image with FROM openjdk:17-slim-bullseye and needed an extra java opts: JAVA_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED"

with this setup it works fine.

https://github.com/apache/pulsar-manager/issues/509#issuecomment-1544740033

**Comment by kocaki** [comment]
Hi,

I am deploying Pulsar in Kubernetes (Azure) and am facing the same issue. I deploy using Helm. Is there a way to solve this for my deployment? If yes, how?

Thanks in advance!

**Comment by kocaki** [comment]
@malaskowski 

```
Pulsar Manager config:

pulsar_manager:
  component: pulsar-manager
  replicaCount: 1
  # True includes annotation for statefulset that contains hash of corresponding configmap, which will cause pods to restart on configmap change
  restartPodsOnConfigMapChange: false
  # nodeSelector:
  # cloud.google.com/gke-nodepool: default-pool
  annotations: {}
  tolerations: []
  gracePeriod: 30
  resources:
    requests:
      memory: 250Mi
      cpu: 0.1
  configData:
    SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
    REDIRECT_HOST: "http://127.0.0.1"
    REDIRECT_PORT: "9527"
    DRIVER_CLASS_NAME: org.postgresql.Driver
    URL: jdbc:postgresql://127.0.0.1:5432/pulsar_manager
    LOG_LEVEL: DEBUG
    ## If you enabled authentication support
    ## JWT_TOKEN: <token>
    ## SECRET_KEY: data:base64,<secret key>
  ## Pulsar manager service
  ## templates/pulsar-manager-service.yaml
  ##
  service:
    type: LoadBalancer
    port: 9527
    targetPort: 9527
    annotations: {}
  ## Pulsar manager ingress
  ## templates/pulsar-manager-ingress.yaml
  ##
  ingress:
    enabled: false
    annotations: {}
    tls:
      enabled: false

      ## Optional. Leave it blank if your Ingress Controller can provide a default certificate.
      secretName: ""

    hostname: ""
    path: "/"

  ## If set use existing secret with specified name to set pulsar admin credentials.
  existingSecretName:
  admin:
    user: pulsar
    password: pulsar

# These are jobs where job ttl configuration is used
# pulsar-helm-chart/charts/pulsar/templates/pulsar-cluster-initialize.yaml
# pulsar-helm-chart/charts/pulsar/templates/bookkeeper-cluster-initialize.yaml
job:
  ttl:
    enabled: false
    secondsAfterFinished: 3600
```

**Comment by splio-rbechon** [comment]
Hello @kocaki 

Do you have this in your helm template file that deployed pulsar manager ?
```
          - name: PULSAR_MANAGER_OPTS
            value: "$(PULSAR_MANAGER_OPTS)
```

On my side, this variable was the root cause of Supervisord issue ... I just removed it to fix my issue

**Comment by kocaki** [comment]
Hi @splio-rbechon,

It is exixting in the pulsar-manager-deployment.yaml but looks different:

```
          - name: PULSAR_MANAGER_OPTS
            value: "$(PULSAR_MANAGER_OPTS) -Dlog4j2.formatMsgNoLookups=true"
```

Tried a new deployment without it but it is still stuck on the same. Logs:

```
Starting PostGreSQL Server
Adding group `pulsar' (GID 1000) ...
Done.
Adding user `pulsar' ...
Adding new user `pulsar' (1000) with group `pulsar' ...
Creating home directory `/home/pulsar' ...
Copying files from `/etc/skel' ...
Changing the user information for pulsar
Enter the new value, or press ENTER for the default
Use of uninitialized value $answer in chop at /usr/sbin/adduser line 582.
Use of uninitialized value $answer in pattern match (m//) at /usr/sbin/adduser line 583.
/pulsar-manager/startup.sh: 21: initdb: not found
/pulsar-manager/startup.sh: 22: pg_ctl: not found
createdb: error: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
	Full Name []: 	Room Number []: 	Work Phone []: 	Home Phone []: 	Other []: Is the information correct? [Y/n] Starting Pulsar Manager Front end
Starting Pulsar Manager Back end
Start Pulsar Manager by specifying a configuration file.
2023-06-08 08:59:30,389 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-06-08 08:59:30,390 INFO supervisord started with pid 64
2023-06-08 08:59:31,393 INFO spawned: 'pulsar-manager-backend' with pid 65
2023-06-08 08:59:32,538 INFO success: pulsar-manager-backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

So with the suggestion of @malaskowski the backend startup problem has been solved but now there is still a db issue.

**Comment by enzo-dechaene** [comment]
It finally started yesterday with pulsar 0.4.0 for me, can you try adding this conf :

``` PASSWORD: pulsar
    USERNAME: pulsar
    REDIRECT_HOST: your_ingress_url
    REDIRECT_PORT: '80'
    URL: jdbc:postgresql://127.0.0.1:5432/pulsar_manager

**Comment by kocaki** [comment]
Hi @enzo-dechaene,

Unfortunately also failing with this setup. Logs show me that the pular_manager_backend keeps restarting. Can you share your pulsar manager config so I can compare?

**Comment by malaskowski** [comment]
@kocaki 
The default `pulsar`/`pulsar` credentials does not work in my project's Pulsar setup. 

I followed the [instructions for creating user via the backend API](https://github.com/apache/pulsar-manager#access-pulsar-manager):

```bash
CSRF_TOKEN=$(kubectl exec --namespace pulsar -it $manager_pod -- curl http://localhost:7750/pulsar-manager/csrf-token)
kubectl exec --namespace pulsar -it $manager_pod -- curl \
-H 'X-XSRF-TOKEN: $CSRF_TOKEN' \
-H 'Cookie: XSRF-TOKEN=$CSRF_TOKEN;' \
-H "Content-Type: application/json" \
-X PUT http://localhost:7750/pulsar-manager/users/superuser \
-d '{"name": "admin", "password": "mypassword", "description": "console admin", "email": "admin@example.com"}'
```

This is also fairly easy to automate.

**Comment by kocaki** [comment]
Hi @malaskowski,

Thanks I will try it. With 0.4.0 I see that the db is being created in the pod but unfortunately the pulsar_manager_backend keeps restarting. 

Are you running the db embedded or using an external db and version 0.3.0 or 0.4.0? Because the embedded db will be destroyed once you redeploy the pod right or will it migrate the db to the new pod?

**Comment by kocaki** [comment]
Hi @enzo-dechaene,

Thanks for the info and help. The problem is that the pulsar-manager-backend keeps restarting and we cannot find out why. 

The config looks as following:

```
  configData:
    REDIRECT_HOST: "http://127.0.0.1"
    REDIRECT_PORT: "80"
    DRIVER_CLASS_NAME: org.postgresql.Driver
    URL: jdbc:postgresql://127.0.0.1:5432/pulsar_manager
    LOG_LEVEL: DEBUG
    SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
    #Workaround for https://github.com/apache/pulsar-manager/issues/505
    PASSWORD: pulsar
    USERNAME: pulsar
    LOG_LEVEL: DEBUG
```
    
I attached the log of the pulsar manager where you can see that db is being created successfully with 0.4.0 but then it the backend keeps restarting so even if I should create a user I am unable to login. 
  
Our configuration is in Azure AKS. When I check the resources I see there is an internal and external ip assigned and necessary ports are set open automatically. Besides Pulsar Manager also the Proxy pod is restarting with the error it cannot start http server on port 80. No idea if it is related to each other. 

 If I install version 0.1.0, I can login on the webinterface but receive a lot of errors (500 internal server error). And with 3.0 there is this known issue regarding the db which this topic is about. 
 
 Tried also an external PostgreSql db but looks like it is not being used. DB stays empty and no errors in log. 

    
[pulsar_manager_1.txt](https://github.com/apache/pulsar-manager/files/11706843/pulsar_manager_1.txt)

**Comment by jesperbagge** [comment]
Just wanted to chip in with what I came out with after a bit of a rabbit chase and how I got things to not repeatledy restart.

On version 0.4.0 (but some of the errrors are probably there in 0.3.0 as well) I found out that `entrypoint.sh` checks if the ENV variable `SPRING_CONFIGURATION_FILE` is configured. If it is, it tries to start supervisord with a reference to this config. However, the `docker/supervisord-configuration-file.conf` is [configured to look for the config file](https://github.com/apache/pulsar-manager/blob/22c8587e641ca524f4edda9ba8444aa5ff494da2/docker/supervisord-configuration-file.conf#L32) in another ENV variable. Namely `ENV_SPRING_CONFIGURATION_FILE` :(

So both those ENV:s has to point to the same config file.

Fixing that, the backend still restarts since the [helm chart for the pulsar manager deployment](https://github.com/apache/pulsar-helm-chart/blob/b3c19fd7fc7067e67940244777dd4241c8295dd4/charts/pulsar/templates/pulsar-manager-deployment.yaml#L93) creates an ENV named `PULSAR_MANAGER_OPTS` that references itself. Also found by @kocaki [here](https://github.com/apache/pulsar-manager/issues/505#issuecomment-1582190167).

So that ENV also has to be fixed.

My final version of the values.yaml file looks like this:

```
pulsar_manager:
  configData:
    ENV_SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
    SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
    PULSAR_MANAGER_OPTS: " -Dlog4j2.formatMsgNoLookups=true"
```

With those three ENV:s configured I managed to get the backend into a running state but still had to manually create a user as described by @malaskowski [here](https://github.com/apache/pulsar-manager/issues/505#issuecomment-1583010641).
